name: Build Deploy

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键：给写入权限！！！
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 关键：必须加！

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        run: |
          yarn install
          yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}